# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Kyrs3\PBZ_6sem\ontologies-editor\exit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 168)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.yes_button = QtWidgets.QPushButton(Dialog)
        self.yes_button.setGeometry(QtCore.QRect(60, 120, 93, 28))
        self.yes_button.setObjectName("yes_button")
        self.no_button = QtWidgets.QPushButton(Dialog)
        self.no_button.setGeometry(QtCore.QRect(220, 120, 93, 28))
        self.no_button.setObjectName("no_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Вы уверены, что хотите выйти без сохранения изменений?"))
        self.yes_button.setText(_translate("Dialog", "Да"))
        self.no_button.setText(_translate("Dialog", "Нет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
